### PASSO 1: Criar um novo usuário
# Corrigido para a porta 8080
POST http://localhost:8080/api/usuarios
Content-Type: application/json

{
    "nome": "Usuário Teste Válido",
    "email": "teste@valido.com",
    "senha": "senha123"
}

### --------------------------------------------------

### PASSO 2: Fazer Login (com o usuário ACIMA)
# @name loginRequest
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "email": "teste@valido.com",
    "senha": "senha123"
}

### --------------------------------------------------

### PASSO 3: Listar todos os usuários (AUTENTICADO)
# Pega o token da resposta do 'loginRequest' acima
@jwt = {{loginRequest.response.body.token}}

GET http://localhost:8080/api/usuarios
Authorization: Bearer {{jwt}}



### 4. Atualizar um usuário existente (PUT)
# Reutiliza o token da requisição 'loginRequest'
PUT http://localhost:8080/api/usuarios/5
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "nome": "Teste Put com token"
}

### --------------------------------------------------

### 5. Deletar (omitir) um usuário (DELETE)
# Reutiliza o token da requisição 'loginRequest'
DELETE http://localhost:8080/api/usuarios/5
Authorization: Bearer {{jwt}}

### --------------------------------------------------

### PASSO 6: Criar um Cartão (precisa de ID de usuário)
# (Vamos assumir que o usuário "teste@valido.com" é o ID 1)
# Você precisa estar logado (ter rodado o PASSO 2)

@jwt = {{loginRequest.response.body.token}}

POST http://localhost:8080/api/cartoes
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "numero": "1111222233335555",
    "validade": "12/30",
    "nomeTitular": "Usuário Teste Válido",
    "usuarioId": 5
}

### --------------------------------------------------
### --------------------------------------------------
### PASSO 7: REGISTRAR TRANSAÇÃO COM LOCALIZAÇÃO
# (Você precisa ter rodado o PASSO 6 para ter um cartão)

POST http://localhost:8080/api/transacoes
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "valor": 50.00,
    "estabelecimento": "Torre Eiffel",
    "cartaoId": 3, 
    "latitude": 48.8584,
    "longitude": 2.2945,
    "ipAddress": "8.8.8.8"
}